<#
Builds fishdata.lua from the fishing tables in the Phoenix server repo.

    git clone https://github.com/phoenixffxi/Phoenix
    powershell -ExecutionPolicy Bypass -File tools\build_fishdata.ps1 -Phoenix C:\path\to\Phoenix

Only the columns the addon needs to mirror fishingutils::FishingCheck are kept.
#>
param(
    [Parameter(Mandatory = $true)][string]$Phoenix,
    [string]$Out
)

$ErrorActionPreference = 'Stop';
if (-not $Out) { $Out = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '..\fishdata.lua'; }
$sql = Join-Path $Phoenix 'sql';

function Split-Values([string]$text) {
    $values = New-Object System.Collections.Generic.List[object];
    $i = 0;
    while ($i -lt $text.Length) {
        $c = $text[$i];
        if ($c -eq ' ' -or $c -eq ',') { $i++; continue; }
        if ($c -eq "'") {
            $sb = New-Object System.Text.StringBuilder;
            $i++;
            while ($i -lt $text.Length) {
                $c = $text[$i];
                if ($c -eq '\') { [void]$sb.Append($text[$i + 1]); $i += 2; continue; }
                if ($c -eq "'") {
                    if ($i + 1 -lt $text.Length -and $text[$i + 1] -eq "'") { [void]$sb.Append("'"); $i += 2; continue; }
                    $i++;
                    break;
                }
                [void]$sb.Append($c);
                $i++;
            }
            $values.Add($sb.ToString());
            continue;
        }
        $start = $i;
        while ($i -lt $text.Length -and $text[$i] -ne ',') { $i++; }
        $values.Add($text.Substring($start, $i - $start).Trim());
    }
    return ,$values;
}

function Read-Rows([string]$table) {
    $rows = New-Object System.Collections.Generic.List[object];
    $pattern = '^INSERT INTO `' + $table + '` VALUES \((.*)\);';
    foreach ($line in [System.IO.File]::ReadAllLines((Join-Path $sql "$table.sql"))) {
        if ($line -match $pattern) {
            $rows.Add((Split-Values $Matches[1]));
        }
    }
    return ,$rows;
}

function Read-Floats([string]$hex) {
    if ($hex -notmatch '^0x([0-9A-Fa-f]+)$') { return @(); }
    $digits = $Matches[1];
    $bytes  = New-Object byte[] ($digits.Length / 2);
    for ($b = 0; $b -lt $bytes.Length; $b++) {
        $bytes[$b] = [Convert]::ToByte($digits.Substring($b * 2, 2), 16);
    }
    $floats = @();
    for ($o = 0; $o + 4 -le $bytes.Length; $o += 4) {
        $floats += [BitConverter]::ToSingle($bytes, $o);
    }
    return $floats;
}

function Lua-String([string]$s) {
    return "'" + ($s -replace '\\', '\\' -replace "'", "\'") + "'";
}

function Lua-Number($n) {
    return ([double]$n).ToString('0.###', [System.Globalization.CultureInfo]::InvariantCulture);
}

$lua = New-Object System.Text.StringBuilder;
function Emit([string]$line) { [void]$lua.AppendLine($line); }

Emit '-- Generated by tools/build_fishdata.ps1 from https://github.com/phoenixffxi/Phoenix. Do not edit by hand.';
Emit 'return {';

# fishing_fish: fishid, name, skill_level, difficulty, base_delay, base_move, min_length, max_length, ranking,
# size_type, water_type, log, quest, quest_status, flags, hour_pattern, moon_pattern, month_pattern, legendary,
# legendary_flags, item, max_hook, rarity, required_keyitem, required_catches, family, quest_only, contest, disabled
$fishIds = @{};
Emit '    fish = {';
foreach ($r in (Read-Rows 'fishing_fish')) {
    if ([int]$r[28] -ne 0 -or [int]$r[8] -ge 99) { continue; }
    $fishIds[[int]$r[0]] = $true;
    $fields = @(
        "name = $(Lua-String $r[1])",
        "skill = $($r[2])",
        "size = $($r[9])",
        "rarity = $($r[22])",
        "hour = $($r[15])",
        "moon = $($r[16])",
        "month = $($r[17])"
    );
    if ([int]$r[20] -ne 0) { $fields += 'item = true'; }
    if (([int]$r[14] -band 1) -ne 0) { $fields += 'shellfish = true'; }
    if ([int]$r[18] -ne 0) { $fields += 'legendary = true'; }
    if ([int]$r[23] -ne 0) { $fields += "keyitem = $($r[23])"; }
    if ([int]$r[11] -lt 255 -and [int]$r[12] -lt 255) { $fields += 'quest = true'; }
    if ([int]$r[26] -ne 0) { $fields += 'quest_only = true'; }
    Emit ("        [{0}] = {{ {1} }}," -f $r[0], ($fields -join ', '));
}
Emit '    },';

# fishing_group: groupid, fishid, rarity, pool_size, restock_rate
$groups = [ordered]@{};
foreach ($r in (Read-Rows 'fishing_group')) {
    $group = [string]$r[0];
    if (-not $fishIds.ContainsKey([int]$r[1])) { continue; }
    if (-not $groups.Contains($group)) { $groups[$group] = New-Object System.Collections.Generic.List[string]; }
    $groups[$group].Add($r[1]);
}
Emit '    groups = {';
foreach ($group in $groups.Keys) {
    Emit ("        [{0}] = {{ {1} }}," -f $group, ($groups[$group] -join ', '));
}
Emit '    },';

# fishing_catch: zoneid, areaid, groupid
$catch = [ordered]@{};
foreach ($r in (Read-Rows 'fishing_catch')) {
    $zone = [string]$r[0];
    if (-not $catch.Contains($zone)) { $catch[$zone] = New-Object System.Collections.Generic.List[string]; }
    $catch[$zone].Add(('[{0}] = {1}' -f $r[1], $r[2]));
}
Emit '    catch = {';
foreach ($zone in $catch.Keys) {
    Emit ("        [{0}] = {{ {1} }}," -f $zone, ($catch[$zone] -join ', '));
}
Emit '    },';

# fishing_area: zoneid, areaid, name, bound_type, bound_height, bound_radius, bounds, center_x, center_y, center_z
$areas = [ordered]@{};
foreach ($r in (Read-Rows 'fishing_area')) {
    $zone = [string]$r[0];
    if (-not $areas.Contains($zone)) { $areas[$zone] = New-Object "System.Collections.Generic.SortedDictionary[int, object]"; }
    $areas[$zone][[int]$r[1]] = $r;
}
Emit '    areas = {';
foreach ($zone in $areas.Keys) {
    Emit "        [$zone] = {";
    foreach ($r in $areas[$zone].Values) {
        $fields = @(
            "id = $($r[1])",
            "name = $(Lua-String $r[2])",
            "type = $($r[3])",
            "height = $($r[4])",
            "radius = $($r[5])",
            "x = $(Lua-Number $r[7])",
            "y = $(Lua-Number $r[8])",
            "z = $(Lua-Number $r[9])"
        );
        $floats = Read-Floats $r[6];
        if ($floats.Count -gt 0) {
            # Trailing all-zero points are padding, the same way LoadFishingAreas trims them.
            $count = 0;
            for ($p = 0; $p + 3 -le $floats.Count; $p += 3) {
                if ($floats[$p] -ne 0 -or $floats[$p + 1] -ne 0 -or $floats[$p + 2] -ne 0) { $count = $p / 3 + 1; }
            }
            $points = @();
            for ($p = 0; $p -lt $count; $p++) {
                $points += ('{{ {0}, {1}, {2} }}' -f (Lua-Number $floats[$p * 3]), (Lua-Number $floats[$p * 3 + 1]), (Lua-Number $floats[$p * 3 + 2]));
            }
            if ($points.Count -gt 0) { $fields += "bounds = { $($points -join ', ') }"; }
        }
        Emit ("            {{ {0} }}," -f ($fields -join ', '));
    }
    Emit '        },';
}
Emit '    },';

# fishing_bait_affinity: baitid, fishid, power
$affinity = [ordered]@{};
foreach ($r in (Read-Rows 'fishing_bait_affinity')) {
    $bait = [string]$r[0];
    if (-not $affinity.Contains($bait)) { $affinity[$bait] = New-Object System.Collections.Generic.List[string]; }
    $affinity[$bait].Add(('[{0}] = {1}' -f $r[1], $r[2]));
}
Emit '    affinity = {';
foreach ($bait in $affinity.Keys) {
    Emit ("        [{0}] = {{ {1} }}," -f $bait, ($affinity[$bait] -join ', '));
}
Emit '    },';

# fishing_bait: baitid, name, type, maxhook, losable, flags, mmm, rankmod
Emit '    baits = {';
foreach ($r in (Read-Rows 'fishing_bait')) {
    Emit ("        [{0}] = {{ name = {1}, type = {2}, flags = {3} }}," -f $r[0], (Lua-String $r[1]), $r[2], $r[5]);
}
Emit '    },';

# fishing_rod: rodid, name, material, size_type, flags, min_rank, max_rank, ... legendary (20), rating
Emit '    rods = {';
foreach ($r in (Read-Rows 'fishing_rod')) {
    $legendary = if ([int]$r[20] -ne 0) { ', legendary = true' } else { '' };
    Emit ("        [{0}] = {{ name = {1}, size = {2}{3} }}," -f $r[0], (Lua-String $r[1]), $r[3], $legendary);
}
Emit '    },';

# fishing_mob: mobid, name, zoneid, level, min_length, max_length, ranking, difficulty, base_delay, base_move,
# log, quest, nm, nm_flags, areaid, rarity, min_respawn, max_respawn, required_baitid, alternative_baitid,
# required_keyitem, quest_only, disabled
$mobs = [ordered]@{};
$seen = @{};
foreach ($r in (Read-Rows 'fishing_mob')) {
    if ([int]$r[22] -ne 0) { continue; }
    $zone   = [string]$r[2];
    $fields = @("name = $(Lua-String ($r[1] -replace '_', ' '))", "area = $($r[14])");
    if ([int]$r[12] -ne 0) { $fields += 'nm = true'; }
    if ([int]$r[18] -ne 0) { $fields += "bait = $($r[18])"; }
    if ([int]$r[19] -ne 0) { $fields += "alt_bait = $($r[19])"; }
    if ([int]$r[10] -lt 255 -and [int]$r[11] -lt 255) { $fields += 'quest = true'; }
    $entry = '{ ' + ($fields -join ', ') + ' }';
    if ($seen.ContainsKey("$zone $entry")) { continue; }
    $seen["$zone $entry"] = $true;
    if (-not $mobs.Contains($zone)) { $mobs[$zone] = New-Object System.Collections.Generic.List[string]; }
    $mobs[$zone].Add($entry);
}
Emit '    mobs = {';
foreach ($zone in $mobs.Keys) {
    Emit ("        [{0}] = {{ {1} }}," -f $zone, ($mobs[$zone] -join ', '));
}
Emit '    },';

Emit '};';

$utf8 = New-Object System.Text.UTF8Encoding($false);
[System.IO.File]::WriteAllText([System.IO.Path]::GetFullPath($Out), $lua.ToString(), $utf8);
Write-Host "Wrote $Out";
